environment: staging
currentRelease: ""
desiredRelease: "971e5338c6839dabe2d6bde49770eab643f06727"
status: deploying
gitopsCommit: ""
lastSuccessfulDeployment: ""
rollback:
  available: false
  target: ""
